import type { GameAttribution } from '../../app/data/attribution-types.js'
import { repositoryCodeLicense } from '../../app/data/attribution-types.js'

export const spotOnAttribution: GameAttribution = {
  slug: 'spot-on',
  name: 'Spot On',
  codeLicense: repositoryCodeLicense,
  entries: [
    {
      title: 'Spot On game logic and rendering',
      type: 'other',
      usedIn: 'Spot On room-tidying interactive toy',
      creator: 'Peninsular Reveries',
      source: 'Original code',
      license: repositoryCodeLicense,
      modifications: 'Not applicable',
      notes: 'Game engine, state management, and room scene rendering.',
    },
    {
      title: 'pick-up-whoosh',
      type: 'sound effect',
      usedIn: 'Spot On item pickup sound',
      creator: 'patchywolf',
      source: 'Freesound',
      sourceUrl: 'https://freesound.org/people/patchywolf/sounds/414/',
      license: 'Creative Commons 0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modifications: 'Trimmed, normalized, high-pass and low-pass filtered, converted to OGG.',
      notes: 'CC0 whoosh sample used for picking up items.',
    },
    {
      title: 'place-thunk',
      type: 'sound effect',
      usedIn: 'Spot On item placement sound',
      creator: 'goldsounds',
      source: 'Freesound',
      sourceUrl: 'https://freesound.org/people/goldsounds/sounds/33508/',
      license: 'Creative Commons 0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modifications: 'Trimmed, normalized, filtered, converted to OGG.',
      notes: 'CC0 thud sample used for placing items on spots.',
    },
    {
      title: 'completion-chime',
      type: 'sound effect',
      usedIn: 'Spot On room completion sound',
      creator: 'carmen_mireles_barrios',
      source: 'Freesound',
      sourceUrl: 'https://freesound.org/people/carmen_mireles_barrios/sounds/395/',
      license: 'Creative Commons 0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modifications: 'Trimmed, normalized, filtered, converted to OGG.',
      notes: 'CC0 chime sample used when all items in a room are placed.',
    },
    {
      title: 'room-transition',
      type: 'sound effect',
      usedIn: 'Spot On room transition sound',
      creator: 'fotosettile',
      source: 'Freesound',
      sourceUrl: 'https://freesound.org/people/fotosettile/sounds/17787/',
      license: 'Creative Commons 0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      modifications: 'Trimmed, normalized, filtered, converted to OGG.',
      notes: 'CC0 swoosh sample used when switching to a new room.',
    },
  ],
}