import { route } from '@remix-run/fetch-router/routes'
import { attributionsPagePath } from './data/attribution-index.js'

export const routes = route({
  home: '/',
  attributions: attributionsPagePath,
  superWordInfo: '/super-word/info/',
  missionOrbitInfo: '/mission-orbit/info/',
  chompersInfo: '/chompers/info/',
  pixelPassportInfo: '/pixel-passport/info/',
  storyTrailInfo: '/story-trail/info/',
  squaresInfo: '/squares/info/',
  waterwallInfo: '/waterwall/info/',
  beatPadInfo: '/beat-pad/info/',
  trainSoundsInfo: '/train-sounds/info/',
  spotOnInfo: '/spot-on/info/',
  peekabooInfo: '/peekaboo/info/',
  copycatInfo: '/copycat/info/',
  dragonsCrunchInfo: '/dragons-crunch/info/',
  mudskipperInfo: '/mudskipper/info/',
  tunaPianoInfo: '/tuna-piano/info/',
  growWithMeInfo: '/grow-with-me/info/',
  missionOrbit: '/mission-orbit/',
  superWord: '/super-word/',
  chompers: '/chompers/',
  pixelPassport: '/pixel-passport/',
  storyTrail: '/story-trail/',
  squares: '/squares/',
  waterwall: '/waterwall/',
  beatPad: '/beat-pad/',
  trainSounds: '/train-sounds/',
  spotOn: '/spot-on/',
  peekaboo: '/peekaboo/',
  copycat: '/copycat/',
  dragonsCrunch: '/dragons-crunch/',
  mudskipper: '/mudskipper/',
  tunaPiano: '/tuna-piano/',
  growWithMe: '/grow-with-me/',
  bakingSimulator: '/baking-simulator/',
  bakingSimulatorInfo: '/baking-simulator/info/',
  allAboard: '/all-aboard/',
  allAboardInfo: '/all-aboard/info/',
  blockAttack: '/block-attack/',
  blockAttackInfo: '/block-attack/info/',
  notFound: '/404.html',
})