import type { Puzzle } from './types.js'

export const PUZZLES: readonly Puzzle[] = [
  {
    answer: 'CAT',
    prompt: "Find the letters to spell the furry pet that purrs and says 'meow'! 🐱",
    hint: 'It has whiskers and a long tail — and loves napping!',
    hintEmoji: '🐱',
    items: [
      { id: 'c0', type: 'letter', char: 'C', emoji: '🌙', label: 'Moon', x: 18, y: 18 },
      { id: 'a0', type: 'letter', char: 'A', emoji: '🍎', label: 'Apple', x: 58, y: 16 },
      { id: 't0', type: 'letter', char: 'T', emoji: '🌲', label: 'Tree', x: 82, y: 30 },
      { id: 'd0', type: 'distractor', emoji: '⭐', label: 'Star', x: 36, y: 34 },
      { id: 'd1', type: 'distractor', emoji: '🌸', label: 'Flower', x: 68, y: 50 },
      { id: 'd2', type: 'distractor', emoji: '🦋', label: 'Butterfly', x: 20, y: 60 },
      { id: 'd3', type: 'distractor', emoji: '🌈', label: 'Rainbow', x: 50, y: 64 },
      { id: 'd4', type: 'distractor', emoji: '🎈', label: 'Balloon', x: 78, y: 65 },
    ],
  },
  {
    answer: 'SUN',
    prompt: 'Find the letters to spell the big, bright, warm thing in the daytime sky! ☀️',
    hint: 'It rises in the east every morning and keeps us warm!',
    hintEmoji: '☀️',
    items: [
      { id: 's0', type: 'letter', char: 'S', emoji: '🐚', label: 'Shell', x: 20, y: 20 },
      { id: 'u0', type: 'letter', char: 'U', emoji: '🪴', label: 'Plant', x: 62, y: 14 },
      { id: 'n0', type: 'letter', char: 'N', emoji: '🌰', label: 'Acorn', x: 82, y: 34 },
      { id: 'd0', type: 'distractor', emoji: '🌊', label: 'Wave', x: 38, y: 40 },
      { id: 'd1', type: 'distractor', emoji: '🌺', label: 'Hibiscus', x: 16, y: 62 },
      { id: 'd2', type: 'distractor', emoji: '🦜', label: 'Parrot', x: 52, y: 65 },
      { id: 'd3', type: 'distractor', emoji: '🍄', label: 'Mushroom', x: 78, y: 64 },
      { id: 'd4', type: 'distractor', emoji: '🎵', label: 'Music', x: 40, y: 26 },
    ],
  },
  {
    answer: 'FROG',
    prompt: "This green jumper loves lily pads and goes 'ribbit'! Find its letters! 🐸",
    hint: "It's green, loves to jump, and lives near ponds!",
    hintEmoji: '🐸',
    items: [
      { id: 'f0', type: 'letter', char: 'F', emoji: '🌸', label: 'Flower', x: 22, y: 17 },
      { id: 'r0', type: 'letter', char: 'R', emoji: '🌈', label: 'Rainbow', x: 62, y: 14 },
      { id: 'o0', type: 'letter', char: 'O', emoji: '🍊', label: 'Orange', x: 15, y: 48 },
      { id: 'g0', type: 'letter', char: 'G', emoji: '🍇', label: 'Grapes', x: 80, y: 40 },
      { id: 'd0', type: 'distractor', emoji: '🦆', label: 'Duck', x: 42, y: 34 },
      { id: 'd1', type: 'distractor', emoji: '🌿', label: 'Leaf', x: 56, y: 62 },
      { id: 'd2', type: 'distractor', emoji: '🐝', label: 'Bee', x: 28, y: 66 },
      { id: 'd3', type: 'distractor', emoji: '💧', label: 'Water', x: 72, y: 65 },
    ],
  },
  {
    answer: 'STAR',
    prompt: 'On a clear night, thousands of these twinkle above you! Find the letters! ⭐',
    hint: 'They twinkle in the night sky — you can even make wishes on them!',
    hintEmoji: '⭐',
    items: [
      { id: 's0', type: 'letter', char: 'S', emoji: '🌻', label: 'Sunflower', x: 16, y: 18 },
      { id: 't0', type: 'letter', char: 'T', emoji: '🌴', label: 'Palm Tree', x: 52, y: 14 },
      { id: 'a0', type: 'letter', char: 'A', emoji: '🍄', label: 'Mushroom', x: 83, y: 24 },
      { id: 'r0', type: 'letter', char: 'R', emoji: '🌹', label: 'Rose', x: 30, y: 50 },
      { id: 'd0', type: 'distractor', emoji: '🌙', label: 'Moon', x: 68, y: 46 },
      { id: 'd1', type: 'distractor', emoji: '🦉', label: 'Owl', x: 20, y: 65 },
      { id: 'd2', type: 'distractor', emoji: '🌌', label: 'Galaxy', x: 55, y: 66 },
      { id: 'd3', type: 'distractor', emoji: '🎆', label: 'Fireworks', x: 78, y: 66 },
    ],
  },
  {
    answer: 'BOOK',
    prompt: 'I have pages and a cover — you read stories inside me! Find my letters! 📚',
    hint: 'You find lots of these in a library!',
    hintEmoji: '📚',
    items: [
      { id: 'b0', type: 'letter', char: 'B', emoji: '🐝', label: 'Bee', x: 18, y: 17 },
      { id: 'o0', type: 'letter', char: 'O', emoji: '🍩', label: 'Donut', x: 55, y: 18 },
      { id: 'o1', type: 'letter', char: 'O', emoji: '🦭', label: 'Seal', x: 82, y: 17 },
      { id: 'k0', type: 'letter', char: 'K', emoji: '🪁', label: 'Kite', x: 32, y: 48 },
      { id: 'd0', type: 'distractor', emoji: '✏️', label: 'Pencil', x: 62, y: 48 },
      { id: 'd1', type: 'distractor', emoji: '📏', label: 'Ruler', x: 16, y: 66 },
      { id: 'd2', type: 'distractor', emoji: '🎒', label: 'Backpack', x: 50, y: 68 },
      { id: 'd3', type: 'distractor', emoji: '🍎', label: 'Apple', x: 78, y: 66 },
    ],
  },
]
