import type { Difficulty, Puzzle, WordSpec } from './types.js'
import { buildPuzzle, randomizePuzzle, shuffleList } from './scene-builder.js'

function words(
  difficulty: Difficulty,
  entries: ReadonlyArray<readonly [string, string, string, string, string, string]>,
): WordSpec[] {
  return entries.map(([answer, hint, theme, phonemicPattern, gradeAlign, sourcesStr]) => ({
    answer,
    difficulty,
    hint,
    theme,
    phonemicPattern,
    gradeAlign,
    sources: sourcesStr.split(','),
  }))
}

const WORD_BANK: Record<Difficulty, WordSpec[]> = {
  // ── Tier 1 — Sidekick (Pre-K / Kindergarten) ─────────────────────────────
  // Criteria: Dolch Pre-Primer/Primer sight words + CVC words, 2–4 letters.
  sidekick: words('sidekick', [
    ['CAT', 'A small furry animal that says "meow."', 'animals', 'CVC', 'K', 'Dolch-PP,Fry-100'],
    ['DOG', 'A fluffy pet that wags its tail.', 'animals', 'CVC', 'K', 'Dolch-PP,Fry-100'],
    ['BUG', 'A tiny crawling creature you find outside.', 'animals', 'CVC', 'K', 'Fry-100'],
    ['SUN', 'The big bright ball in the sky.', 'nature', 'CVC', 'K', 'Dolch-PP,Fry-100'],
    ['HAT', 'You wear this on top of your head.', 'clothing', 'CVC', 'K', 'Fry-100'],
    ['MAP', 'A picture that shows where things are.', 'objects', 'CVC', 'K', 'Fry-100'],
    ['CUP', 'You drink water from this.', 'objects', 'CVC', 'K', 'Fry-100'],
    ['JAM', 'A sweet spread you put on bread.', 'food', 'CVC', 'K', 'Fry-100'],
    ['BED', 'You sleep in this at night.', 'home', 'CVC', 'K', 'Dolch-PP,Fry-100'],
    ['BOX', 'A square container you can put things in.', 'objects', 'CVC', 'K', 'Fry-100'],
    ['MOP', "This cleans the floor when it's wet.", 'home', 'CVC', 'K', 'Fry-100'],
    ['PIG', 'A pink farm animal that goes "oink."', 'animals', 'CVC', 'K', 'Fry-100'],
    ['HEN', 'A mother chicken that lays eggs.', 'animals', 'CVC', 'K', 'Fry-100'],
    ['WEB', 'A spider makes this sticky net.', 'nature', 'CVC', 'K', 'Fry-100'],
    ['JET', 'A very fast airplane.', 'vehicles', 'CVC', 'K', 'Fry-100'],
    ['MUD', 'Wet dirt you might find after rain.', 'nature', 'CVC', 'K', 'Fry-100'],
    ['NUT', 'A small hard shell with a seed inside.', 'food', 'CVC', 'K', 'Fry-100'],
    ['PAD', 'A flat thing you write on.', 'objects', 'CVC', 'K', 'Fry-100'],
    ['RUG', 'A soft mat on the floor.', 'home', 'CVC', 'K', 'Fry-100'],
    ['TUG', 'To pull something hard.', 'action', 'CVC', 'K', 'Fry-100'],
    ['KIT', 'A little set of tools.', 'objects', 'CVC', 'K', 'Fry-100'],
    ['LEG', 'You use these to walk and run.', 'body-safe', 'CVC', 'K', 'Fry-100'],
    ['ZAP', 'A quick flash of energy.', 'action', 'CVC', 'K', 'Fry-100'],
    ['HOP', 'To jump on one foot.', 'action', 'CVC', 'K', 'Dolch-PP,Fry-100'],
    ['DIG', 'To use a shovel to move dirt.', 'action', 'CVC', 'K', 'Fry-100'],
    ['SAP', 'The sticky juice inside a tree.', 'nature', 'CVC', 'K', 'Fry-100'],
    ['COT', 'A small folding bed.', 'home', 'CVC', 'K', 'Fry-100'],
    ['YAK', 'A big shaggy animal from the mountains.', 'animals', 'CVC', 'K', 'Fry-100'],
    ['FIG', 'A sweet little fruit.', 'food', 'CVC', 'K', 'Fry-100'],
    ['GEM', 'A shiny precious stone.', 'objects', 'CVC', 'K', 'Fry-100'],
    ['VET', 'A doctor for animals.', 'people', 'CVC', 'K', 'Fry-100'],
    ['ZIP', 'To close something fast, like a zipper.', 'action', 'CVC', 'K', 'Fry-100'],
    ['HIP', 'The side of your body above your leg.', 'body-safe', 'CVC', 'K', 'Fry-100'],
    ['DIP', 'To put something into sauce or water.', 'action', 'CVC', 'K', 'Fry-100'],
    ['ROD', 'A long thin stick.', 'objects', 'CVC', 'K', 'Fry-100'],
    ['THE', 'The most common word in English — it points to something specific.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['AND', 'A word that joins two things together.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['FOR', 'A word that tells why or who something is for.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['YOU', 'Another word for the person reading this!', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['ALL', 'Every single one.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['CAN', 'Able to do something.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['HER', 'Belonging to a girl.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['NOT', 'A word that means no or the opposite.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['BUT', 'A word that shows two things are different.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['ONE', 'The number after zero.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['OUT', 'On the other side — not inside.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['DAY', 'The time when the sun is up.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['NOW', 'At this very moment.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['WHO', 'A question word asking about a person.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['WAY', 'The path or direction to go.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
    ['HOW', 'A question word asking about the way something is done.', 'sight', 'sight', 'K', 'Dolch-PP,Fry-100'],
  ]),

  // ── Tier 2 — Hero (Kindergarten / Grade 1) ───────────────────────────────
  // Criteria: CVC mastery + initial consonant blends and digraphs (sh, ch, th, wh). 3–5 letters.
  hero: words('hero', [
    ['FROG', 'A green jumping animal that lives near ponds.', 'animals', 'CCVC-blend-fr', 'K-Gr1', 'Fry-100'],
    ['STAR', 'A tiny dot of light you see at night.', 'nature', 'CCVC-blend-st', 'K-Gr1', 'Fry-100,Dolch-Gr1'],
    ['SHIP', 'A big boat that sails on the ocean.', 'vehicles', 'CVCC-digraph-sh', 'K-Gr1', 'Fry-100'],
    ['CRAB', 'A sideways-walking creature with claws.', 'animals', 'CCVC-blend-cr', 'K-Gr1', 'Fry-100'],
    ['DRUM', 'You hit this to make a beat.', 'music', 'CCVC-blend-dr', 'K-Gr1', 'Fry-100'],
    ['CLAM', 'A shellfish that lives in the sand.', 'animals', 'CCVC-blend-cl', 'K-Gr1', 'Fry-100'],
    ['FLAG', 'A colorful piece of cloth on a pole.', 'objects', 'CCVC-blend-fl', 'K-Gr1', 'Fry-100'],
    ['GRIN', 'A big wide smile.', 'action', 'CCVC-blend-gr', 'K-Gr1', 'Fry-100'],
    ['PLAN', 'An idea for what to do.', 'action', 'CCVC-blend-pl', 'K-Gr1', 'Dolch-Gr1'],
    ['SWIM', 'To move through water with your arms and legs.', 'action', 'CCVC-blend-sw', 'K-Gr1', 'Dolch-Gr1'],
    ['SNAP', 'To break something quickly with a sharp sound.', 'action', 'CCVC-blend-sn', 'K-Gr1', 'Fry-100'],
    ['DRIP', 'A tiny drop falling slowly.', 'nature', 'CCVC-blend-dr', 'K-Gr1', 'Fry-100'],
    ['STEM', 'The stalk that holds a flower up.', 'nature', 'CCVC-blend-st', 'K-Gr1', 'Fry-100'],
    ['CLIP', 'A small fastener that holds things together.', 'objects', 'CCVC-blend-cl', 'K-Gr1', 'Fry-100'],
    ['CHIP', 'A thin crunchy snack.', 'food', 'CCVC-blend-ch', 'K-Gr1', 'Fry-100'],
    ['SHOP', 'A place where you buy things.', 'places', 'CVCC-digraph-sh', 'K-Gr1', 'Dolch-Gr1,Fry-100'],
    ['FLAT', 'Even and smooth with no bumps.', 'descriptive', 'CCVC-blend-fl', 'K-Gr1', 'Fry-100'],
    ['SLIM', 'Very thin and narrow.', 'descriptive', 'CCVC-blend-sl', 'K-Gr1', 'Fry-100'],
    ['TWIN', 'One of two people born at the same time.', 'people', 'CCVC-blend-tw', 'K-Gr1', 'Fry-100'],
    ['BLOB', 'A round wobbly shape.', 'shapes', 'CCVC-blend-bl', 'K-Gr1', 'Fry-100'],
    ['FISH', 'An animal that swims and has scales and fins.', 'animals', 'CVCC-digraph-sh', 'K-Gr1', 'Dolch-PP,Fry-100'],
    ['CHAT', 'To talk in a friendly, easy way.', 'action', 'CVCC-digraph-ch', 'K-Gr1', 'Fry-100'],
    ['CHOP', 'To cut something into pieces.', 'action', 'CVCC-digraph-ch', 'K-Gr1', 'Fry-100'],
    ['THIS', 'A word pointing to something close by.', 'sight-digraph', 'digraph-th', 'K-Gr1', 'Dolch-PP,Fry-100'],
    ['WHEN', 'A question word about time.', 'sight-digraph', 'digraph-wh', 'K-Gr1', 'Dolch-Gr1,Fry-100'],
    ['GLAD', 'Feeling very happy.', 'descriptive', 'CCVC-blend-gl', 'K-Gr1', 'Dolch-Gr1'],
    ['SLED', 'A vehicle that slides on snow.', 'vehicles', 'CCVC-blend-sl', 'K-Gr1', 'Fry-100'],
    ['TRIP', 'A journey to somewhere fun.', 'action', 'CCVC-blend-tr', 'K-Gr1', 'Fry-100'],
    ['PROP', 'Something used in a play or show.', 'objects', 'CCVC-blend-pr', 'K-Gr1', 'Fry-100'],
    ['SKIP', 'To hop along in a bouncy way.', 'action', 'CCVC-blend-sk', 'K-Gr1', 'Fry-100'],
    ['STEP', 'To put one foot forward.', 'action', 'CCVC-blend-st', 'K-Gr1', 'Dolch-Gr1,Fry-100'],
    ['SPIN', 'To turn around very quickly.', 'action', 'CCVC-blend-sp', 'K-Gr1', 'Fry-200'],
    ['SCAN', 'To look quickly over something.', 'action', 'CCVC-blend-sc', 'K-Gr1', 'Fry-100'],
    ['SLUG', 'A slow, slimy garden creature.', 'animals', 'CCVC-blend-sl', 'K-Gr1', 'Fry-100'],
    ['PLOP', 'The sound something makes falling into water.', 'sound', 'CCVC-blend-pl', 'K-Gr1', 'Fry-100'],
    ['SHED', 'A small hut in the garden.', 'places', 'CVCC-digraph-sh', 'K-Gr1', 'Fry-100'],
    ['CHIN', 'The bottom part of your face below your mouth.', 'body-safe', 'CVC-digraph-ch', 'K-Gr1', 'Fry-200'],
    ['THEN', 'After that; next.', 'sight-digraph', 'digraph-th', 'K-Gr1', 'Dolch-Gr1,Fry-100'],
    ['THAT', 'Pointing to something a little farther away.', 'sight-digraph', 'digraph-th', 'K-Gr1', 'Dolch-PP,Fry-100'],
    ['THEM', 'Those people or things over there.', 'sight-digraph', 'digraph-th', 'K-Gr1', 'Dolch-Gr1,Fry-100'],
    ['WHIZ', 'To zoom past super quickly.', 'action', 'digraph-wh', 'K-Gr1', 'Fry-200'],
    ['SHIN', 'The front part of your lower leg.', 'body-safe', 'CVCC-digraph-sh', 'K-Gr1', 'Fry-200'],
    ['BRIM', 'The edge along the top of something.', 'objects', 'CCVC-blend-br', 'K-Gr1', 'Fry-100'],
    ['GRAB', 'To reach out and take hold of something.', 'action', 'CCVC-blend-gr', 'K-Gr1', 'Fry-100'],
    ['SNUG', 'Warm and cozy, like a blanket.', 'descriptive', 'CCVC-blend-sn', 'K-Gr1', 'Fry-200'],
    ['TWIG', 'A tiny branch from a tree.', 'nature', 'CCVC-blend-tw', 'K-Gr1', 'Fry-100'],
    ['FLED', 'Ran away very fast.', 'action', 'CCVC-blend-fl', 'K-Gr1', 'Fry-200'],
    ['SLIP', 'To slide and almost fall down.', 'action', 'CCVC-blend-sl', 'K-Gr1', 'Fry-200'],
    ['GRIP', 'To hold on to something tightly.', 'action', 'CCVC-blend-gr', 'K-Gr1', 'Fry-200'],
  ]),

  // ── Tier 3 — Super (Grade 1 / Grade 2) ───────────────────────────────────
  // Criteria: CVCe (silent-e) and common vowel teams (ee, oa, ai, ea, oo). 3–5 letters.
  super: words('super', [
    ['CAKE', 'A sweet baked treat for birthdays.', 'food', 'CVCe', 'Gr1-2', 'Fry-100,Dolch-Gr1'],
    ['BIKE', 'A two-wheeled vehicle you pedal.', 'vehicles', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['HOME', 'The place where your family lives.', 'places', 'CVCe', 'Gr1-2', 'Dolch-Gr1,Fry-100'],
    ['CUTE', 'Small and sweet-looking.', 'descriptive', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['HIVE', 'The buzzing home of honeybees.', 'nature', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['MOLE', 'A small furry animal that digs tunnels.', 'animals', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['PINE', 'A tall tree with needles and pinecones.', 'nature', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['ROSE', 'A beautiful flower with a nice smell.', 'nature', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['CAPE', 'A long flowing cloth worn like a superhero.', 'clothing', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['DUNE', 'A hill made of sand near the ocean.', 'nature', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['FAME', 'Being known by lots of people.', 'descriptive', 'CVCe', 'Gr1-2', 'Fry-200'],
    ['GATE', 'A door in a fence or wall.', 'objects', 'CVCe', 'Gr1-2', 'Fry-200'],
    ['LAKE', 'A body of water surrounded by land.', 'nature', 'CVCe', 'Gr1-2', 'Fry-100,Dolch-Gr1'],
    ['LIME', 'A green sour citrus fruit.', 'food', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['NOSE', 'The part of your face you smell with.', 'body-safe', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['POLE', 'A long thin stick standing straight up.', 'objects', 'CVCe', 'Gr1-2', 'Fry-100'],
    ['SAFE', 'Protected from harm.', 'descriptive', 'CVCe', 'Gr1-2', 'Fry-100,Dolch-Gr1'],
    ['TALE', 'A story, like a fairy tale.', 'objects', 'CVCe', 'Gr1-2', 'Fry-200'],
    ['VOTE', 'To choose someone by raising your hand or marking a paper.', 'concepts', 'CVCe', 'Gr1-2', 'Fry-200'],
    ['ZONE', 'A special area or region.', 'places', 'CVCe', 'Gr1-2', 'Fry-200'],
    ['TREE', 'A tall plant with a trunk and branches.', 'nature', 'vowel-team-ee', 'Gr1-2', 'Dolch-PP,Fry-100'],
    ['BOAT', 'Something that floats and carries you on water.', 'vehicles', 'vowel-team-oa', 'Gr1-2', 'Fry-100'],
    ['RAIN', 'Water that falls from clouds.', 'nature', 'vowel-team-ai', 'Gr1-2', 'Fry-100,Dolch-Gr1'],
    ['BEAD', 'A small round ball you can put on a string.', 'objects', 'vowel-team-ea', 'Gr1-2', 'Fry-100'],
    ['DEEP', 'Going very far down.', 'descriptive', 'vowel-team-ee', 'Gr1-2', 'Fry-200'],
    ['FOAM', 'Soft bubbly stuff, like on top of a wave.', 'nature', 'vowel-team-oa', 'Gr1-2', 'Fry-200'],
    ['GOAL', 'Something you are trying to do or achieve.', 'concepts', 'vowel-team-oa', 'Gr1-2', 'Fry-200'],
    ['HEAT', 'Warmth from the sun or a fire.', 'nature', 'vowel-team-ea', 'Gr1-2', 'Fry-200'],
    ['LEAF', 'A flat green part of a plant.', 'nature', 'vowel-team-ea', 'Gr1-2', 'Fry-100'],
    ['MEAT', 'Food that comes from animals.', 'food', 'vowel-team-ea', 'Gr1-2', 'Fry-100'],
    ['MOAT', 'A deep water channel around a castle.', 'places', 'vowel-team-oa', 'Gr1-2', 'Fry-200'],
    ['PEEL', 'The outer skin of a fruit.', 'food', 'vowel-team-ee', 'Gr1-2', 'Fry-200'],
    ['ROAD', 'A flat path for cars and bikes.', 'places', 'vowel-team-oa', 'Gr1-2', 'Dolch-Gr1,Fry-100'],
    ['SEAL', 'A slippery sea creature with flippers.', 'animals', 'vowel-team-ea', 'Gr1-2', 'Fry-200'],
    ['TOAD', 'A bumpy frog-like creature.', 'animals', 'vowel-team-oa', 'Gr1-2', 'Fry-200'],
    ['FEEL', 'To touch or sense something.', 'action', 'vowel-team-ee', 'Gr1-2', 'Dolch-Gr1,Fry-100'],
    ['SEED', 'A tiny thing planted in the ground to grow.', 'nature', 'vowel-team-ee', 'Gr1-2', 'Fry-100'],
    ['PEEK', 'To take a tiny secret look.', 'action', 'vowel-team-ee', 'Gr1-2', 'Fry-200'],
    ['MEET', 'To come together with someone.', 'action', 'vowel-team-ee', 'Gr1-2', 'Dolch-Gr1,Fry-100'],
    ['NEED', 'Something very important that you must have.', 'sight', 'vowel-team-ee', 'Gr1-2', 'Dolch-Gr1,Fry-100'],
    ['WEED', 'An unwanted plant in the garden.', 'nature', 'vowel-team-ee', 'Gr1-2', 'Fry-200'],
    ['TAIL', 'The part at the back end of an animal.', 'animals', 'vowel-team-ai', 'Gr1-2', 'Fry-200'],
    ['MAIL', 'Letters and packages delivered to your door.', 'objects', 'vowel-team-ai', 'Gr1-2', 'Fry-200'],
    ['NAIL', 'A small metal spike you hammer into wood.', 'objects', 'vowel-team-ai', 'Gr1-2', 'Fry-200'],
    ['PAID', 'Gave money in return for something.', 'concepts', 'vowel-team-ai', 'Gr1-2', 'Fry-200'],
    ['RAIL', 'A bar that you hold for balance.', 'objects', 'vowel-team-ai', 'Gr1-2', 'Fry-200'],
    ['SAIL', 'The big cloth on a boat that catches wind.', 'vehicles', 'vowel-team-ai', 'Gr1-2', 'Fry-200'],
    ['WAIL', 'To cry loudly.', 'action', 'vowel-team-ai', 'Gr1-2', 'Fry-200'],
    ['BOON', 'A helpful or lucky thing.', 'concepts', 'vowel-team-oo', 'Gr1-2', 'Fry-200'],
    ['COOL', 'Not too warm, not too cold — just right.', 'descriptive', 'vowel-team-oo', 'Gr1-2', 'Fry-100'],
    ['MOON', 'The big glowing circle in the night sky.', 'nature', 'vowel-team-oo', 'Gr1-2', 'Fry-100'],
  ]),

  // ── Tier 4 — Ultra (Grade 2 / Grade 3) ───────────────────────────────────
  // Criteria: R-controlled vowels (ar, er, ir, or, ur) + simple 2-syllable words. 4–6 letters.
  ultra: words('ultra', [
    ['BIRD', 'A feathered creature that can fly and sings songs.', 'animals', 'r-controlled-ir', 'Gr2-3', 'Fry-100,Dolch-Gr2'],
    ['BURN', 'What happens when something gets too hot.', 'action', 'r-controlled-ur', 'Gr2-3', 'Fry-200'],
    ['FARM', 'A place in the country where animals and crops are raised.', 'places', 'r-controlled-ar', 'Gr2-3', 'Fry-100,Dolch-Gr2'],
    ['FIRM', 'Solid and hard when you press it.', 'descriptive', 'r-controlled-ir', 'Gr2-3', 'Fry-200'],
    ['FORK', 'The tool you use to eat your dinner.', 'objects', 'r-controlled-or', 'Gr2-3', 'Fry-200'],
    ['HORN', 'A curved animal feature used for defense.', 'animals', 'r-controlled-or', 'Gr2-3', 'Fry-200'],
    ['HURT', 'Feeling pain from an injury.', 'descriptive', 'r-controlled-ur', 'Gr2-3', 'Dolch-Gr2,Fry-200'],
    ['PARK', 'A green outdoor place to play.', 'places', 'r-controlled-ar', 'Gr2-3', 'Fry-100,Dolch-Gr2'],
    ['PORT', 'A place where ships dock near the shore.', 'places', 'r-controlled-or', 'Gr2-3', 'Fry-200'],
    ['SURF', 'Riding waves on a board at the ocean.', 'action', 'r-controlled-ur', 'Gr2-3', 'Fry-200'],
    ['TERM', 'A word or period of time with a specific meaning.', 'concepts', 'r-controlled-er', 'Gr2-3', 'Fry-200'],
    ['TURN', 'To spin or change direction.', 'action', 'r-controlled-ur', 'Gr2-3', 'Dolch-Gr2,Fry-100'],
    ['VERB', 'An action word in a sentence.', 'concepts', 'r-controlled-er', 'Gr2-3', 'Fry-200'],
    ['WORM', 'A wiggly creature that lives in the soil.', 'animals', 'r-controlled-or', 'Gr2-3', 'Fry-200'],
    ['BARK', 'The rough outer layer of a tree trunk.', 'nature', 'r-controlled-ar', 'Gr2-3', 'Fry-200'],
    ['CART', 'A small vehicle you push at the market.', 'vehicles', 'r-controlled-ar', 'Gr2-3', 'Fry-200'],
    ['DART', 'A small pointed object thrown at a target.', 'objects', 'r-controlled-ar', 'Gr2-3', 'Fry-200'],
    ['FORD', 'A shallow crossing point in a river.', 'nature', 'r-controlled-or', 'Gr2-3', 'Fry-200'],
    ['GERM', 'A tiny invisible thing that can make you sick.', 'science', 'r-controlled-er', 'Gr2-3', 'Fry-200'],
    ['HERD', 'A group of animals moving together.', 'animals', 'r-controlled-er', 'Gr2-3', 'Fry-200'],
    ['LARK', 'A small songbird that sings high in the sky.', 'animals', 'r-controlled-ar', 'Gr2-3', 'Fry-200'],
    ['BORN', 'To come into the world.', 'concepts', 'r-controlled-or', 'Gr2-3', 'Dolch-Gr2,Fry-200'],
    ['TORN', 'Ripped apart.', 'descriptive', 'r-controlled-or', 'Gr2-3', 'Fry-200'],
    ['CURB', 'The edge of the sidewalk.', 'places', 'r-controlled-ur', 'Gr2-3', 'Fry-200'],
    ['TURF', 'The grassy ground.', 'nature', 'r-controlled-ur', 'Gr2-3', 'Fry-200'],
    ['CABIN', 'A cozy little house in the woods.', 'places', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['DAISY', 'A cheerful white and yellow flower.', 'nature', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['HAPPY', 'Feeling really good and smiling inside.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Dolch-Gr2,Fry-100'],
    ['JELLY', 'A jiggly, wiggly sweet food.', 'food', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['LUCKY', 'Getting something good by chance.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['MAGIC', 'Something that seems impossible but wonderful.', 'concepts', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['MERRY', 'Happy and full of fun.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Dolch-Gr3,Fry-300'],
    ['MUDDY', 'Covered in wet dirt.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['PAPER', 'A flat sheet you write or draw on.', 'objects', '2-syllable-open', 'Gr2-3', 'Dolch-Gr3,Fry-100'],
    ['ROCKY', 'Covered with lots of rocks.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['SUNNY', 'Bright and warm with lots of sunshine.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['WINDY', 'When the wind is blowing strongly.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['CANDY', 'A sweet treat.', 'food', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['FANCY', 'Decorated in a special way.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['HANDY', 'Useful and easy to use.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['KITTY', 'A small sweet cat.', 'animals', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['PENNY', 'A small copper coin.', 'objects', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['POPPY', 'A bright red flower in a field.', 'nature', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['PUPPY', 'A baby dog.', 'animals', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['RAINY', 'When there is a lot of rain falling.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['SANDY', 'Covered with soft sand.', 'descriptive', '2-syllable-open', 'Gr2-3', 'Fry-300'],
    ['EARLY', 'Before the usual time — sunrise is early!', 'descriptive', 'r-controlled-er+2syl', 'Gr2-3', 'Dolch-Gr2,Fry-200'],
    ['EVERY', 'Each one without leaving any out.', 'sight', 'r-controlled-er+2syl', 'Gr2-3', 'Dolch-Gr2,Fry-100'],
    ['ORDER', 'The way things are arranged in a line.', 'concepts', 'r-controlled-or+2syl', 'Gr2-3', 'Fry-200'],
    ['RIVER', 'A flowing body of water.', 'nature', 'r-controlled-er+2syl', 'Gr2-3', 'Fry-200,Dolch-Gr2'],
  ]),

  // ── Tier 5 — Legend (Grade 3+) ────────────────────────────────────────────
  // Criteria: Complex clusters, multi-syllable, fluent reader vocabulary. 5–7 letters.
  legend: words('legend', [
    ['ACORN', 'A tiny seed from an oak tree that squirrels love.', 'nature', '2-syllable-open', 'Gr3+', 'Fry-300'],
    ['BLAND', 'Without much taste or excitement.', 'descriptive', 'blend-bl+nasal', 'Gr3+', 'Fry-300'],
    ['BLAZE', 'A bright roaring fire or a flash of light.', 'nature', 'CCVCe-blend', 'Gr3+', 'Fry-300'],
    ['BRAVE', 'Ready to face scary things without running.', 'descriptive', 'CCVCe-blend', 'Gr3+', 'Fry-300'],
    ['BREAD', 'A baked food made from flour — great with butter.', 'food', 'CCVCC-blend', 'Gr3+', 'Fry-200'],
    ['CHESS', 'A board game of strategy played with pieces.', 'objects', 'digraph-cluster', 'Gr3+', 'Fry-300'],
    ['CHIEF', 'The leader of a group.', 'people', 'digraph-ie', 'Gr3+', 'Fry-300'],
    ['CLASH', 'When two things hit each other hard.', 'action', 'blend-cl+digraph', 'Gr3+', 'Fry-300'],
    ['COAST', 'The land along the edge of the ocean.', 'nature', 'vowel-oa+blend', 'Gr3+', 'Fry-300'],
    ['CORAL', 'A colorful sea creature that looks like a plant.', 'nature', '2-syllable', 'Gr3+', 'Fry-300'],
    ['CRANE', 'A tall bird with long legs, or a machine that lifts things.', 'animals', 'CCVCe-blend-cr', 'Gr3+', 'Fry-300'],
    ['CRISP', 'Cool and fresh, or crunchy food.', 'descriptive', 'CCVCC-cluster', 'Gr3+', 'Fry-300'],
    ['CROSS', 'To go from one side to another.', 'action', 'blend-cr+double', 'Gr3+', 'Fry-200,Dolch-Gr3'],
    ['CRUST', 'The hard outer part of bread or pie.', 'food', 'CCVCC-blend', 'Gr3+', 'Fry-300'],
    ['EMBER', 'A glowing piece of coal in a dying fire.', 'nature', '2-syllable-er', 'Gr3+', 'Fry-300'],
    ['FEAST', 'A very large and delicious meal.', 'food', 'vowel-ea+blend', 'Gr3+', 'Fry-300'],
    ['FLAME', 'The glowing part of a fire.', 'nature', 'CCVCe-blend-fl', 'Gr3+', 'Fry-300'],
    ['FLASK', 'A container for carrying liquid.', 'objects', 'CCVCC-blend', 'Gr3+', 'Fry-300'],
    ['FLOAT', 'To rest on water without sinking.', 'action', 'vowel-oa+blend', 'Gr3+', 'Fry-300'],
    ['FLUTE', 'A long tube-shaped instrument you blow across.', 'music', 'CCVCe-blend-fl', 'Gr3+', 'Fry-300'],
    ['FROST', 'Ice crystals that form on cold mornings.', 'nature', 'blend-fr+cluster', 'Gr3+', 'Fry-300'],
    ['GHOST', 'A spooky floating spirit — but friendly ones exist!', 'fantasy', 'blend-silent-gh', 'Gr3+', 'Fry-300'],
    ['GLARE', 'A very bright light that hurts your eyes.', 'nature', 'CCVCe-blend-gl', 'Gr3+', 'Fry-300'],
    ['GLEAM', 'A soft bright light that shines and sparkles.', 'nature', 'vowel-ea-blend', 'Gr3+', 'Fry-300'],
    ['GLIDE', 'To move smoothly and silently through the air.', 'action', 'CCVCe-blend-gl', 'Gr3+', 'Fry-300'],
    ['GLOBE', 'A round model of the Earth.', 'objects', 'CCVCe-blend-gl', 'Gr3+', 'Fry-300'],
    ['GRACE', 'Moving in a smooth, beautiful way.', 'descriptive', 'CCVCe-blend-gr', 'Gr3+', 'Fry-300'],
    ['GRAND', 'Very large or impressive.', 'descriptive', 'blend-gr+nasal', 'Gr3+', 'Dolch-Gr3,Fry-200'],
    ['GRASP', 'To hold tightly with the hand.', 'action', 'blend-gr+cluster', 'Gr3+', 'Fry-300'],
    ['GRAZE', 'To eat grass slowly, like a cow in a field.', 'action', 'CCVCe-blend-gr', 'Gr3+', 'Fry-300'],
    ['GRIEF', 'Deep sadness.', 'concepts', 'vowel-ie-blend', 'Gr3+', 'Fry-300'],
    ['GROVE', 'A small group of trees.', 'nature', 'CCVCe-blend-gr', 'Gr3+', 'Fry-300'],
    ['GROWL', 'The low rumbling sound an animal makes.', 'animals', 'vowel-ow-blend', 'Gr3+', 'Fry-300'],
    ['GARDEN', 'A patch of land where flowers or vegetables grow.', 'nature', '2-syllable-ar', 'Gr3+', 'Fry-300'],
    ['PLANET', 'A giant ball that travels around a star.', 'science', '2-syllable-blend', 'Gr3+', 'Fry-300'],
    ['ROCKET', 'A vehicle that blasts into outer space.', 'vehicles', '2-syllable-ck', 'Gr3+', 'Fry-300'],
    ['CASTLE', 'A big stone fortress from long ago.', 'places', '2-syllable-blend', 'Gr3+', 'Fry-300'],
    ['COMET', 'A ball of ice and rock that flies through space.', 'science', '2-syllable', 'Gr3+', 'Fry-300'],
    ['CACTUS', 'A prickly plant that stores water in the desert.', 'nature', '2-syllable-cluster', 'Gr3+', 'Fry-300'],
    ['BOTTLE', 'A glass or plastic container for liquids.', 'objects', '2-syllable', 'Gr3+', 'Fry-300'],
    ['CANDLE', 'A wax stick with a wick that burns.', 'objects', '2-syllable-blend', 'Gr3+', 'Fry-300'],
    ['CIRCLE', 'A perfectly round shape.', 'shapes', '2-syllable-r-control', 'Gr3+', 'Fry-300'],
    ['GOBLIN', 'A small mischievous creature in fairy tales.', 'fantasy', '2-syllable-blend', 'Gr3+', 'Fry-300'],
    ['HARBOR', 'A sheltered bay where boats stay.', 'places', '2-syllable-ar', 'Gr3+', 'Fry-300'],
    ['JUNGLE', 'A thick, hot forest full of animals.', 'nature', '2-syllable-blend', 'Gr3+', 'Fry-300'],
    ['KITTEN', 'A baby cat.', 'animals', '2-syllable', 'Gr3+', 'Fry-300'],
    ['MARBLE', 'A small colorful glass ball used in games.', 'objects', '2-syllable-ar', 'Gr3+', 'Fry-300'],
    ['MIRROR', 'A smooth surface that shows your reflection.', 'objects', '2-syllable-ir', 'Gr3+', 'Fry-300'],
    ['PENCIL', 'A tool for writing and drawing.', 'objects', '2-syllable-blend', 'Gr3+', 'Fry-300'],
    ['PIRATE', 'A daring sailor who sails the high seas.', 'people', '2-syllable-CVCe', 'Gr3+', 'Fry-300'],
    ['PUZZLE', 'A game where you fit pieces together.', 'objects', '2-syllable-blend', 'Gr3+', 'Fry-300'],
    ['RABBIT', 'A fluffy-eared animal that hops.', 'animals', '2-syllable', 'Gr3+', 'Fry-300'],
    ['RIDDLE', 'A tricky question with a clever answer.', 'concepts', '2-syllable', 'Gr3+', 'Fry-300'],
    ['SILVER', 'A shiny white metal, or the color of moonlight.', 'descriptive', '2-syllable-er', 'Gr3+', 'Dolch-Gr3,Fry-300'],
    ['SCROLL', 'A rolled-up paper with writing on it.', 'objects', 'CCVCC-blend', 'Gr3+', 'Fry-300'],
    ['SECRET', 'Something known only to a few people.', 'concepts', '2-syllable-ee', 'Gr3+', 'Fry-300'],
  ]),
}

/** Full puzzle pool — all difficulties combined */
export const PUZZLES: readonly Puzzle[] = Object.values(WORD_BANK)
  .flatMap((specs) => specs.map((spec) => buildPuzzle(spec)))

/** Number of puzzles to randomly select for a session when no filter is provided */
export const DEFAULT_SESSION_SIZE = 5

/**
 * Select a shuffled five-puzzle round for the requested difficulty.
 */
export function selectPuzzles(difficulty: Difficulty): Puzzle[] {
  const filtered = PUZZLES.filter((puzzle) => puzzle.difficulty === difficulty)
  const pool = filtered.length > 0 ? filtered : PUZZLES

  return shuffleList(pool)
    .slice(0, Math.min(DEFAULT_SESSION_SIZE, pool.length))
    .map((puzzle) => randomizePuzzle(puzzle))
}
