import type { Difficulty } from './types.js'

export type WordTheme =
  | 'animals'
  | 'everyday'
  | 'food'
  | 'home'
  | 'nature'
  | 'play'
  | 'sky'
  | 'space'
  | 'travel'
  | 'water'

export interface WordSpec {
  readonly answer: string
  readonly difficulty: Difficulty
  readonly hint: string
  readonly theme: WordTheme
}

function wordSpecs(
  difficulty: Difficulty,
  entries: ReadonlyArray<readonly [string, string, WordTheme]>,
): WordSpec[] {
  return entries.map(([answer, hint, theme]) => ({ answer, difficulty, hint, theme }))
}

export const WORD_BANK: Readonly<Record<Difficulty, readonly WordSpec[]>> = {
  starter: wordSpecs('starter', [
    ['GO', 'Time to move from here to there.', 'everyday'],
    ['UP', 'The opposite of down.', 'everyday'],
    ['IN', 'The opposite of out.', 'everyday'],
    ['ON', 'What a light is after you switch it.', 'everyday'],
    ['NO', 'The opposite of yes.', 'everyday'],
    ['HI', 'A friendly hello.', 'everyday'],
    ['ME', 'A word for yourself.', 'everyday'],
    ['WE', 'A word for you and me together.', 'everyday'],
    ['DO', 'A tiny word that means to act.', 'everyday'],
    ['TO', 'A tiny helper word for going somewhere.', 'everyday'],
    ['BE', 'A tiny word that means to exist.', 'everyday'],
    ['MY', 'A word that shows something belongs to you.', 'everyday'],
    ['BY', 'A tiny word for being near something.', 'everyday'],
    ['IT', 'A tiny word for a thing.', 'everyday'],
    ['AM', 'A tiny word you use about yourself right now.', 'everyday'],
    ['US', 'A word for a group that includes me.', 'everyday'],
    ['OR', 'A tiny word for choosing this or that.', 'everyday'],
    ['HE', 'A word for a boy or a man.', 'everyday'],
    ['IF', 'A tiny word for maybe.', 'everyday'],
    ['SO', 'A tiny word for very much.', 'everyday'],
    ['AT', 'A tiny word for a place.', 'everyday'],
    ['OF', 'A tiny helper word for belonging.', 'everyday'],
    ['AN', 'A tiny word that means one.', 'everyday'],
    ['AS', 'A tiny word for being alike.', 'everyday'],
    ['IS', 'A tiny word for what something is right now.', 'everyday'],
  ]),
  easy: wordSpecs('easy', [
    ['CAT', 'A furry pet that purrs.', 'animals'],
    ['SUN', 'The big bright thing in the daytime sky.', 'sky'],
    ['DOG', 'A loyal pet that loves fetch.', 'animals'],
    ['BUG', 'A tiny crawly creature with six legs.', 'animals'],
    ['HAT', 'Something you wear on your head.', 'home'],
    ['PIG', 'A pink farm animal that oinks.', 'animals'],
    ['CUP', 'Something you drink from.', 'home'],
    ['BEE', 'A buzzy insect that makes honey.', 'animals'],
    ['BED', 'The cozy place where you sleep.', 'home'],
    ['HEN', 'A farm bird that lays eggs.', 'animals'],
    ['MAP', 'A guide that helps you find the way.', 'travel'],
    ['COW', 'A farm animal that says moo.', 'animals'],
    ['FOX', 'A clever orange animal with a fluffy tail.', 'animals'],
    ['JAM', 'A sweet fruit spread for toast.', 'food'],
    ['BOX', 'A shape with sides that can hold toys.', 'home'],
    ['NUT', 'A crunchy snack with a shell.', 'food'],
    ['RUG', 'A soft mat for the floor.', 'home'],
    ['CAR', 'A vehicle that drives on roads.', 'travel'],
    ['BUS', 'A big vehicle for many riders.', 'travel'],
    ['SKY', 'The blue space high above you.', 'sky'],
    ['WEB', 'A sticky spider net.', 'animals'],
    ['LOG', 'A piece of a fallen tree trunk.', 'nature'],
    ['ANT', 'A tiny worker insect.', 'animals'],
    ['FIN', 'A fish part that helps it swim.', 'water'],
    ['PEN', 'Something you write with.', 'home'],
    ['TEN', 'A number after nine.', 'everyday'],
    ['MAN', 'A grown-up boy.', 'everyday'],
    ['VAN', 'A roomy road vehicle.', 'travel'],
    ['BAT', 'A night animal with wings.', 'animals'],
    ['RAT', 'A small animal with a long tail.', 'animals'],
    ['PIN', 'A tiny sharp thing that can hold cloth.', 'home'],
    ['MOP', 'A tool for cleaning floors.', 'home'],
    ['JUG', 'A big cup with a handle.', 'home'],
    ['HOP', 'A little jump.', 'play'],
    ['DIG', 'Use your hands or a shovel to make a hole.', 'nature'],
    ['FAN', 'Something that blows cool air.', 'home'],
    ['WIG', 'Hair you can put on.', 'play'],
    ['POT', 'A bowl for cooking food.', 'home'],
    ['TOP', 'The highest part of something.', 'everyday'],
    ['HUG', 'A squeeze with your arms.', 'everyday'],
  ]),
  medium: wordSpecs('medium', [
    ['FROG', 'A green jumper that says ribbit.', 'animals'],
    ['STAR', 'A tiny twinkle in the night sky.', 'space'],
    ['BOOK', 'Something with pages full of stories.', 'home'],
    ['FISH', 'A shiny swimmer with fins.', 'water'],
    ['CAKE', 'A sweet treat for birthdays.', 'food'],
    ['BIRD', 'A feathered friend that sings.', 'animals'],
    ['TREE', 'A tall plant with a trunk and leaves.', 'nature'],
    ['MOON', 'A bright circle in the night sky.', 'space'],
    ['BEAR', 'A big furry animal that loves honey.', 'animals'],
    ['RAIN', 'Water drops that fall from clouds.', 'sky'],
    ['BOAT', 'Something that floats on the water.', 'water'],
    ['LION', 'A big cat with a mighty roar.', 'animals'],
    ['WOLF', 'A wild animal that howls.', 'animals'],
    ['SNOW', 'Soft white flakes in winter.', 'sky'],
    ['FARM', 'A place where crops grow and animals live.', 'nature'],
    ['KITE', 'A toy that flies in the wind.', 'play'],
    ['SHIP', 'A huge boat for the sea.', 'water'],
    ['LAMP', 'A light that sits on a table.', 'home'],
    ['ROSE', 'A flower with petals and thorns.', 'nature'],
    ['DUCK', 'A water bird with a bill.', 'animals'],
    ['LEAF', 'A green part that grows on a branch.', 'nature'],
    ['MILK', 'A drink that can come from a cow.', 'food'],
    ['COAT', 'A jacket you wear outside.', 'home'],
    ['WIND', 'Moving air you can feel.', 'sky'],
    ['NEST', 'A bird home made of twigs.', 'animals'],
    ['FERN', 'A leafy green plant.', 'nature'],
    ['POND', 'A small pool of water.', 'water'],
    ['BELL', 'Something that rings ding-dong.', 'home'],
    ['DRUM', 'An instrument you tap.', 'play'],
    ['FLAG', 'A cloth sign on a pole.', 'travel'],
    ['CRAB', 'A side-walking sea animal.', 'water'],
    ['PLUM', 'A small purple fruit.', 'food'],
    ['WORM', 'A tiny wriggly ground animal.', 'animals'],
    ['ROCK', 'A hard stone from the ground.', 'nature'],
    ['GIFT', 'A present for someone.', 'play'],
    ['MASK', 'Something you wear over your face.', 'play'],
    ['RING', 'A round band for a finger.', 'home'],
    ['LAND', 'The ground, not the sea.', 'nature'],
    ['SWIM', 'Move through water.', 'water'],
    ['HAND', 'The part at the end of your arm.', 'everyday'],
  ]),
  hard: wordSpecs('hard', [
    ['OCEAN', 'A giant body of salty water.', 'water'],
    ['MOUSE', 'A tiny squeaky animal with big ears.', 'animals'],
    ['TIGER', 'A striped big cat.', 'animals'],
    ['CLOUD', 'A fluffy shape floating in the sky.', 'sky'],
    ['PLANT', 'A living green thing that grows in soil.', 'nature'],
    ['SNAKE', 'A long slithery reptile with no legs.', 'animals'],
    ['HORSE', 'A fast animal you can ride.', 'animals'],
    ['TRAIN', 'A choo-choo vehicle on tracks.', 'travel'],
    ['LEMON', 'A sour yellow fruit.', 'food'],
    ['DREAM', 'A story your mind makes while you sleep.', 'everyday'],
    ['BEACH', 'A sandy place by the water.', 'water'],
    ['APPLE', 'A crunchy fruit that can be red or green.', 'food'],
    ['FLAME', 'A hot flicker from a fire.', 'nature'],
    ['HEART', 'The part of your body that pumps blood.', 'everyday'],
    ['LIGHT', 'What helps you see in the dark.', 'home'],
    ['RIVER', 'Water that flows between two banks.', 'water'],
    ['SHEEP', 'A woolly farm animal that says baa.', 'animals'],
    ['STONE', 'A hard little rock.', 'nature'],
    ['GRASS', 'Green blades that cover a lawn.', 'nature'],
    ['HOUSE', 'The place where people live.', 'home'],
    ['STORM', 'Dark clouds with wild wind and rain.', 'sky'],
    ['CROWN', 'A shiny hat for a king or queen.', 'play'],
    ['QUEEN', 'A royal ruler with a crown.', 'play'],
    ['ROBIN', 'A small bird with a red chest.', 'animals'],
    ['EARTH', 'The ground beneath your feet.', 'nature'],
    ['TABLE', 'A place to sit and eat.', 'home'],
    ['STOVE', 'Where pots get hot for cooking.', 'home'],
    ['WHEEL', 'A round part that helps things roll.', 'travel'],
    ['TOOTH', 'A white part you use to bite.', 'everyday'],
    ['CABIN', 'A small house made of wood.', 'home'],
    ['BRICK', 'A hard block used to build walls.', 'home'],
    ['CHALK', 'A stick used for drawing or writing.', 'play'],
    ['GRAPE', 'A small juicy fruit on a vine.', 'food'],
    ['CRANE', 'A tall bird with long legs.', 'animals'],
    ['SKATE', 'A boot with wheels or a blade.', 'play'],
  ]),
  expert: wordSpecs('expert', [
    ['FLOWER', 'A colorful bloom with petals.', 'nature'],
    ['GARDEN', 'A place where flowers and veggies grow.', 'nature'],
    ['CANDLE', 'A wax light with a little flame.', 'home'],
    ['ROCKET', 'A vehicle that blasts into space.', 'space'],
    ['PLANET', 'A huge world that circles a star.', 'space'],
    ['BRIDGE', 'A structure that helps you cross over.', 'travel'],
    ['SPRING', 'The season when flowers begin to bloom.', 'nature'],
    ['WINTER', 'The cold season for coats and snow.', 'sky'],
    ['AUTUMN', 'The season of colorful falling leaves.', 'nature'],
    ['TURTLE', 'A shelled animal that moves slowly.', 'animals'],
    ['CASTLE', 'A giant stone home with towers.', 'play'],
    ['KITTEN', 'A baby cat.', 'animals'],
    ['SUMMER', 'The hot season with sunny days.', 'sky'],
    ['POCKET', 'A little pouch in your clothes.', 'home'],
    ['BUBBLE', 'A wobbly round sphere of soap.', 'play'],
    ['RABBIT', 'A soft animal with long ears.', 'animals'],
    ['SUNSET', 'When the sun goes down.', 'sky'],
    ['BASKET', 'A woven holder with an open top.', 'home'],
    ['FOREST', 'A place full of many trees.', 'nature'],
    ['WINDOW', 'A clear opening you can look through.', 'home'],
    ['PENCIL', 'A tool for writing and drawing.', 'home'],
    ['DRAGON', 'A make-believe creature with wings.', 'play'],
    ['PILLOW', 'A soft cushion for your head.', 'home'],
    ['MAGNET', 'Something that can pull metal.', 'home'],
    ['DONKEY', 'A sturdy animal with long ears.', 'animals'],
    ['PARROT', 'A bright bird that can copy sounds.', 'animals'],
    ['MARBLE', 'A small glass ball for play.', 'play'],
    ['SPIDER', 'An eight-legged web maker.', 'animals'],
    ['BUTTON', 'A little fastener on clothes.', 'home'],
    ['BEAVER', 'An animal that builds dams.', 'animals'],
  ]),
}